### ISSUE TITLE
Default dom element getter

### ISSUE THREAD

**Issue by internettrans** [ariesjia/single-spa-riot#1]
Hey @ariesjia, awesome work! I saw your PR to single-spa.js.org and am excited about bringing riotjs support to single-spa. I took a quick look at your code and it looks good.

One thing that we've been recently doing with our helper libraries such as single-spa-react and single-spa-angular is adding a default dom element getter function, so that the user doesn't have to pass one in on their own. The  default dom element is just an empty div appended to the document.body.

See [single-spa-react's implementation](https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L146-L175) for an example of this.

Also see related https://github.com/CanopyTax/single-spa-inspector/issues/17 which will make it so that when people use the default dom element getter the single-spa-inspector browser extension will automatically be able to show an overlay for that application.

**Comment by ariesjia** [comment]
@joeldenning Thanks for your advice ,  I added the default element getter function yet. 
See [Commit:b927321](https://github.com/ariesjia/single-spa-riot/commit/b9273212f9217b879621a2b825e79642f3b9526f)
That's really let user easy to use
Thanks

**Comment by internettrans** [comment]
Amazing
