### ISSUE TITLE
Github and NPM permissions

### ISSUE THREAD

**Issue by internettrans** [ariesjia/single-spa-riot#5]
Hey @ariesjia, in order to maintain and support this project for the entire single-spacommunity, could you give me Read/Write access on Github and "owner" permissions on npm?

My github/npm username is `joeldenning`. To give me npm access, you can run the following command:

```sh
npm owner add joeldenning single-spa-riot
```

Thanks!

**Comment by ariesjia** [comment]
both github and npm added.  you can check it.
Thanks

**Comment by internettrans** [comment]
👍 thanks! I checked and yeah both look good.
